# Generated by Django 4.0.4 on 2022-05-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
